# Generated by Django 5.2.4 on 2025-08-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос и Ответ', 'verbose_name_plural': 'Вопросы и Ответы'},
        ),
    ]
